export const stoneEscrowAbi = [
  {
    type: 'function',
    name: 'approveAndPayMilestone',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'jobId', type: 'uint256' },
      { name: 'milestoneIndex', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'createJob',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'freelancer', type: 'address' },
      { name: 'title', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'milestoneTitles', type: 'string[]' },
      { name: 'milestoneAmounts', type: 'uint256[]' },
    ],
    outputs: [{ name: 'jobId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'depositFunds',
    stateMutability: 'payable',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getJob',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'client', type: 'address' },
          { name: 'freelancer', type: 'address' },
          { name: 'title', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'totalAmount', type: 'uint256' },
          { name: 'fundedAmount', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'exists', type: 'bool' },
          { name: 'milestoneCount', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getJobProgress',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [
      { name: 'totalMilestones', type: 'uint256' },
      { name: 'paidMilestones', type: 'uint256' },
      { name: 'totalPaid', type: 'uint256' },
      { name: 'remainingEscrow', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getMilestones',
    stateMutability: 'view',
    inputs: [{ name: 'jobId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple[]',
        components: [
          { name: 'title', type: 'string' },
          { name: 'amount', type: 'uint256' },
          { name: 'approved', type: 'bool' },
          { name: 'paid', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'jobCounter',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'jobs',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'client', type: 'address' },
      { name: 'freelancer', type: 'address' },
      { name: 'title', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'totalAmount', type: 'uint256' },
      { name: 'fundedAmount', type: 'uint256' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'exists', type: 'bool' },
      { name: 'milestoneCount', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'FundsDeposited',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'client', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'JobCreated',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'client', type: 'address', indexed: true },
      { name: 'freelancer', type: 'address', indexed: true },
      { name: 'totalAmount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MilestoneApproved',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'milestoneIndex', type: 'uint256', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MilestonePaid',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'milestoneIndex', type: 'uint256', indexed: true },
      { name: 'freelancer', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
] as const;
